{% set data = load_setup_py_data() %}

package:
  name: openalea.sconsx
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python {{PY_VER}}
    - openalea.deploy
  host:
    - python {{PY_VER}}
    - scons

test:
  imports:
    - SCons
    - openalea.sconsx

about:
  home: {{ data.get('url') }}
  license: Cecill-c License
  summary: 'SConsX is an extension package of the SCons build tool. SConsX aims to simplify the build of complex multi-platform packages.'

