name: sconsx
channels:
  - openalea3
  - conda-forge

dependencies:
  - python=3.12
  - scons
  - sphinx
  - sphinx-copybutton
  - sphinx-favicon
  - nbsphinx
  - myst-parser
  - pydata-sphinx-theme
  - sphinx-autodoc-typehints
  - pip
  - pip:
    - -e ..
