name: Building and publish package using anaconda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-and-publish:
    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [macos-latest, linux-latest, windows-latest]
        python-minor-version: [7,8,9,10] 
    steps:
    - uses: actions/checkout@v3
    - name: Build and Publish
      uses: openalea/action-build-publish-anaconda@0.1.1
      with:
        conda: conda
        python: ${{ matrix.python-minor-version }}
        channels: openalea3, conda-forge
        token: ${{ secrets.ANACONDA_TOKEN }}
