name: Building Package

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    uses: openalea/github-action-conda-build/.github/workflows/conda-package-build.yml@main
    with:
      operating-system: '["ubuntu-latest"]'
      python-minor-version: '[9, 10, 11, 12]'
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
